### ISSUE TITLE
Make hardcoded UI-strings translatable

### ISSUE THREAD

**Issue by marcjansen** [terrestris/BasiGX#25]
Currently a lot of string that'll end up visible to the user are not configurable or translatable. We need to change that.

**Comment by weskamm** [comment]
I had to add requires for the inline viewmodels of our classes in #32 to get the modern builds working.
These viewmodels, binds and requires should be removed when implementing a translation functionality in the future.

**Comment by dnlkoch** [comment]
See #68.
