### ISSUE TITLE
Remove eslint-config-openlayers dependency

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/BasiGX#278]
Obviously the latest version of `eslint-config-openlayers` isn't compatible with `BasiGX` anymore, e.g. it is assumed that the project runs inside an `ES6` environment. Therefore we should remove the dependency while preserving the desired `ESlint` configurations by merging them into the project's `.eslintrc`.

See #277.

**Comment by weskamm** [comment]
fixed by #310
