### ISSUE TITLE
moveFeature in util.Animate not working in production build of ol3

### ISSUE THREAD

**Issue by weskamm** [terrestris/BasiGX#35]
The moveFeature method fails when using a production build of ol3, as the property `flatCoordinates` of a `geometry` only exists in a ol-debug version:

https://github.com/terrestris/BasiGX/blob/master/src/util/Animate.js#L103

**Comment by marcjansen** [comment]
This method only works for points, right? Why don't we use the API method [`getCoordinates()`](http://openlayers.org/en/v3.11.2/apidoc/ol.geom.Point.html#getCoordinates)? Will this work?

**Comment by weskamm** [comment]
May work, need to test it...

**Comment by weskamm** [comment]
Fixed by #55
