### ISSUE TITLE
WFS Filters not working with a MapServer 7 backend

### ISSUE THREAD

**Issue by geographika** [terrestris/BasiGX#357]
The OGC filters currently generated by BasiGX.util.WFS cause errors when requesting features from MapServer (with a GET request) such as:

`msWFSGetFeature(): WFS server error. Invalid or Unsupported FILTER in GetFeature : <Filter><BBOX><PropertyName>msGeometry</PropertyName><Envelope><gml:lowerCorner>-1399714.8619581475 6740828.650413123</gml:lowerCorner>      <gml:upperCorner>-289237.7150311069 7405525.048381017</gml:upperCorner></gml:Envelope></ogc:BBOX><gml:Envelope xmlns:gml=http://www.opengis.net/gml srsName=EPSG:3857><gml:lowerCorner>-1399714.8619581475 6740828.650413123</gml:lowerCorner><gml:upperCorner>-289237.7150311069 7405525.048381017</gml:upperCorner><Envelope></BBOX><Filter>
`

It appears these are caused by the following:

- any namespace properties in a tag e.g. xmlns:gml=http://www.opengis.net/gml
- an additional AND wrapper around the filter
- use of BBOX and Intersects?

An example of a working BBOX filter is:
`
<Filter><BBOX><PropertyName>msGeometry</PropertyName><Box%20srsName='EPSG:3857'><coordinates>-1009073.7780155,6855880.1040363 -754844.22198452,6990867.8959637</coordinates></Box></BBOX></Filter>
`

The above problems may be a MapServer issue rather than invalid filters.

**Comment by marcjansen** [comment]
I think this isn't a mapserver bug, but sth. in BasiGX
