### ISSUE TITLE
Release v1.0.5 / v1.1.0

### ISSUE THREAD

**Issue by chrismayer** [terrestris/BasiGX#487]
It would be very helpful to have another release (either v1.0.5 or better v1.1.0), so the very cool 
CSW-form to retrieve WMS layers through an OGC CSW (3d0f9c6) would become usable with a npm installed version of BasiGX.

Thanks for this cool feature!

**Comment by dnlkoch** [comment]
Release is available [now](https://www.npmjs.com/package/@terrestris/basigx/v/1.1.0).
