### ISSUE TITLE
v1.0.4 not published at npmjs.com

### ISSUE THREAD

**Issue by chrismayer** [terrestris/BasiGX#488]
The version [v1.0.4](https://github.com/terrestris/BasiGX/releases/tag/v1.0.4) of BasiGX is not publishes at https://www.npmjs.com/package/@terrestris/basigx

![grafik](https://user-images.githubusercontent.com/1185547/62941941-8811d880-bdd7-11e9-825d-ebd1d70c835e.png)

**Comment by dnlkoch** [comment]
Correct, there is an issue with our release procedure. Closing this in favour of #503.
