### ISSUE TITLE
Wrong version number published to npm

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/BasiGX#503]
Using the current [release script](https://github.com/terrestris/BasiGX/blob/master/package.json#L49) will lead to a release with an invalid version number on npmjs.com.

Reason: Because the target files will be copied to the `dist` folder **before** the version number will be increased by `np`, the package will be released with the preexisting verison number.

Note: The release of version 1.1.0 has been fixed manually.

**Comment by LukasLohoff** [comment]
Right now the npm release script doesn't work at all. It fails with 

```
  ✔ Prerequisite check
  ✔ Git
  ↓ Cleanup [skipped]
  ✔ Prerequisite check
  ✔ Git
  ↓ Cleanup [skipped]
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✖ Publishing package using npm
    → The project was rolled back to its previous state.
    Pushing tags
    Creating release draft on GitHub

✖ Error publishing package:
Command failed with exit code 1: npm publish dist
```

To do a manual release we currently have to:

- bump the version in package.json and commit & push the changes
- draft a new release on https://github.com/terrestris/BasiGX/releases
- change the version in `dist/package.json` 
- run `npm publish`

**Comment by marcjansen** [comment]
We should release a new version anyhow, so we cam revisit hiw this is right now.

**Comment by simonseyock** [comment]
The problem was that the package was built to dist and then the current package.json was copied to dist. Then the version bump was performed in the original package.json and the np tried to publish with the old one.

I fixed this with: `"postversion": "cp package.json dist/",`.
