### ISSUE TITLE
CoordinateMousePositionPanel starts with NaN

### ISSUE THREAD

**Issue by geographika** [terrestris/BasiGX#521]
The `BasiGX.view.panel.CoordinateMousePositionPanel` starts with the X and Y text boxes displaying NaN and a red error underline as shown below:

![coords](https://user-images.githubusercontent.com/490840/66460972-4bc9c400-ea78-11e9-8566-cb18f6ecb35a.png)

To avoid the red error underlining when opening the app the view model can be set to show zeros instead:

```
            viewModel: {
                data: {
                    xVal: 0,
                    yVal: 0
                }
```

Alternatively the map's starting center could be used (pull request to follow).

**Comment by dnlkoch** [comment]
Closed via #522.
