### ISSUE TITLE
Changes in GeoExt are not considered

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/BasiGX#7]
As the BasiGX.pkg contains the GeoExt.pkg changes to GeoExt are not considered.

This leeds to the following problem:

Having an app which requires BasiGX (and GeoExt) you can not get the current GeoExt.pkg because if you build your app sencha fetches the packages and gets GeoExt (outdated) from BasiGX and not from the correct GeoExt repo.

Maybe this is realted to the changes from c1a15d9

**Comment by marcjansen** [comment]
A problem indeed, @KaiVolland.

Once we have versions for the packages, this will be partly solved, as we do not expect changes to often and it's a good thing that packages depend on fixed things.

For now this can be easily done by just retriggering a travis build on master (once GeoExt has changed). This will update `gh-pages` and the package will include the newest GeoExt.
